<x-app-layout>
    <x-slot name="header">Reports</x-slot>
    @include('components.page-styles')

    {{-- Flash messages --}}
    @if(session('success'))
        <div class="alert alert-success">
            <svg width="16" height="16" fill="none" viewBox="0 0 24 24"><path d="M22 11.08V12a10 10 0 11-5.93-9.14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><polyline points="22 4 12 14.01 9 11.01" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
            {{ session('success') }}
        </div>
    @endif

    {{-- Page Header --}}
    <div class="page-hdr">
        <div class="page-hdr-left">
            <div class="page-hdr-title">Report History</div>
            <div class="page-hdr-sub">Access previously generated reports and summaries</div>
        </div>
        <a href="{{ route('reports.create') }}" class="btn btn-primary">
            <svg width="15" height="15" fill="none" viewBox="0 0 24 24"><path d="M12 5v14M5 12h14" stroke="currentColor" stroke-width="2.5" stroke-linecap="round"/></svg>
            Generate New Report
        </a>
    </div>

    <div class="card">
        <div class="card-header">
            <span class="card-title">Recent Reports</span>
        </div>

        @if($reports->count())
        <div style="overflow-x:auto;">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>Date Generated</th>
                        <th>Report Type</th>
                        <th>Generated By</th>
                        <th>Parameters</th>
                        <th style="text-align:right;">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($reports as $report)
                    <tr>
                        <td style="font-weight:600;">{{ $report->generated_date->format('M d, Y H:i') }}</td>
                        <td>
                            <span class="badge badge-info" style="text-transform:uppercase;">{{ str_replace('_', ' ', $report->type) }}</span>
                        </td>
                        <td>{{ $report->user->name }}</td>
                        <td>
                            <span style="font-size:0.75rem;color:var(--text-secondary);">
                                @if(isset($report->parameters['start_date']))
                                    {{ $report->parameters['start_date'] }} to {{ $report->parameters['end_date'] }}
                                @else
                                    Standard Summary
                                @endif
                            </span>
                        </td>
                        <td>
                            <div class="actions-cell" style="justify-content:flex-end;">
                                <a href="{{ asset('storage/' . $report->file_path) }}" target="_blank" class="btn btn-ghost btn-sm">
                                    <svg width="13" height="13" fill="none" viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3" stroke="currentColor" stroke-width="2" stroke-linecap="round"/></svg>
                                    Download
                                </a>
                            </div>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
        @else
            <div class="empty-state">
                <svg width="48" height="48" fill="none" viewBox="0 0 24 24"><path d="M9 17v-2m3 2v-4m3 2v-6M21 12a9 9 0 11-18 0 9 9 0 0118 0z" stroke="currentColor" stroke-width="1.5"/></svg>
                <h3>No reports yet</h3>
                <p>Generate your first report to see it in the history.</p>
                <a href="{{ route('reports.create') }}" class="btn btn-primary">Generate Report</a>
            </div>
        @endif
    </div>
</x-app-layout>
