<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $title }}</title>
    <style>
        body { font-family: 'Helvetica', 'Arial', sans-serif; color: #333; font-size: 12px; line-height: 1.5; }
        .header { text-align: center; margin-bottom: 30px; border-bottom: 2px solid #6366f1; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #6366f1; font-size: 24px; text-transform: uppercase; }
        .header p { margin: 5px 0 0; color: #666; }
        
        .meta { margin-bottom: 20px; }
        .meta-row { display: table; width: 100%; margin-bottom: 5px; }
        .meta-label { display: table-cell; font-weight: bold; width: 120px; }
        .meta-value { display: table-cell; }

        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #f8fafc; border: 1px solid #e2e8f0; padding: 10px; text-align: left; font-weight: bold; color: #475569; }
        td { border: 1px solid #e2e8f0; padding: 10px; vertical-align: top; }
        tr:nth-child(even) { background-color: #fdfdfd; }

        .text-right { text-align: right; }
        .font-bold { font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 10px; }
        
        .badge { padding: 3px 8px; border-radius: 4px; font-size: 10px; font-weight: bold; }
        .badge-success { background-color: #dcfce7; color: #166534; }
        .badge-danger { background-color: #fee2e2; color: #991b1b; }
        .badge-warning { background-color: #fef3c7; color: #92400e; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <p>Generated by StockPro Management System</p>
    </div>

    <div class="meta">
        <div class="meta-row">
            <div class="meta-label">Date Generated:</div>
            <div class="meta-value">{{ now()->format('d M Y, H:i') }}</div>
        </div>
        <div class="meta-row">
            <div class="meta-label">Generated By:</div>
            <div class="meta-value">{{ Auth::user()->name }}</div>
        </div>
        <div class="meta-row">
            <div class="meta-label">Report Type:</div>
            <div class="meta-value">{{ ucfirst($type) }}</div>
        </div>
    </div>

    <table>
        <thead>
            <tr>
                @foreach($headers as $header)
                    <th class="{{ $header == 'Price' || $header == 'Total' || $header == 'Qty' ? 'text-right' : '' }}">
                        {{ $header }}
                    </th>
                @endforeach
            </tr>
        </thead>
        <tbody>
            @foreach($data as $row)
            <tr>
                @foreach($row as $key => $cell)
                    <td class="{{ $key == 'price' || $key == 'total' || $key == 'qty' ? 'text-right' : '' }}">
                        {{ $cell }}
                    </td>
                @endforeach
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        © {{ date('Y') }} StockPro. Confidential Information. Page 1 of 1
    </div>
</body>
</html>
